import {
  allura,
  bruno_ace,
  jacques_francois_shadow,
  noto_sans,
} from "@/utils/fonts";
import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Provider } from "jotai";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${jacques_francois_shadow.variable} ${allura.variable} ${noto_sans.variable} ${bruno_ace.variable}`}>
      <body>
        <Provider>
          <Providers>{children}</Providers>
        </Provider>
      </body>
    </html>
  );
}
